ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
from django.conf import settings
from django.conf.urls.static import static
app_name="cart"
urlpatterns = [

    path('add/<p>',views.add_to_cart,name="add_to_cart"),
    path('cart_remove/<p>', views.cart_remove, name="cart_remove"),
    path('full_remove/<p>', views.full_remove, name="full_remove"),
    path('cart_view', views.cart_view, name="cart_view"),
    path('order_form',views.order_form,name="order_form"),
    path('orderview',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
from django.conf import settings
from django.conf.urls.static import static
app_name="search"
urlpatterns = [

    path('searchresult',views.searchresult,name="searchresult"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
from django.conf import settings
from django.conf.urls.static import static
app_name="shop"
urlpatterns = [
path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout', views.user_logout, name="logout"),

    path('',views.allprodcat,name="allprodcat"),
    path('allproducts/<c>',views.allproducts,name="allproducts"),
path('detail/<p>',views.detail,name="detail"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models

from shop.models import Product
from django.contrib.auth.models import User
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    noofitems=models.IntegerField()
    address=models.TextField(max_length=200)
    phone=models.CharField(max_length=200)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    date_added=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username
    def subtotal(self):
        return self.noofitems*self.product.price


class Account(models.Model):
    acctnumber=models.IntegerField()
    accttype=models.CharField(max_length=200)
    balance=models.IntegerField()

    def __str__(self):
        return str(self.acctnumber)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

class Category(models.Model):
    cname=models.CharField(max_length=200)
    description=models.TextField()
    image=models.ImageField(upload_to='shop/category',null=True,blank=True)

    def __str__(self):
        return self.cname

class Product(models.Model):
    pname = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='shop/product', null=True, blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.pname

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from cart.models import Cart
from shop.models import Product
from django.contrib.auth.decorators import login_required
from cart.models import Account,Order
@login_required
def add_to_cart(request,p):
    product=Product.objects.get(pname=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=product)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
        cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(product=product,user=user,quantity=1)
        cart.save()
    return redirect('cart:cart_view')

@login_required
def cart_view(request):
    total=0
    user=request.user
    try:

        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.product.price
    except:
        pass


    return render(request,'cartview.html',{'cart':cart,'total':total})

@login_required
def cart_remove(request,p):
    product=Product.objects.get(pname=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=product)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()

        else:
            cart.delete()
    except:
        pass
    return redirect('cart:cart_view')
@login_required
def full_remove(request,p):
    product = Product.objects.get(pname=p)
    user = request.user
    try:
        cart = Cart.objects.get(user=user,product=product)
        cart.delete()
    except:
        pass
    return redirect('cart:cart_view')

@login_required
def order_form(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        user=request.user
        cart=Cart.objects.filter(user=user)
        total=0
        for i in cart:
            total+=i.quantity*i.product.price

        acct=Account.objects.get(acctnumber=n)
        if(acct.balance>=total):
            acct.balance=acct.balance-total
            acct.save()
            for i in cart:
                o=Order.objects.create(user=user,product=i.product,phone=p,address=a,noofitems=i.quantity,order_status="paid")
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()
            msg="Order Placed Successfully"


            return render(request,'orderconfirm.html',{'msg':msg})
        else:
            msg="Insufficient Amount.You can't Place Order"
            return render(request, 'orderconfirm.html', {'msg': msg})
    return render(request,'orderform.html')

def orderview(request):
    user=request.user

    o=Order.objects.filter(user=user)


    return render(request,'orderview.html',{'o':o,'u':user.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def searchresult(request):

    products=None
    if(request.method=="POST"):
        query=request.POST['q']
        if query:
            products=Product.objects.filter(Q(pname__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'p':products,'q':query})

ecommerce/shop/views.py
from django.shortcuts import render
from shop.models import Category,Product
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
def allprodcat(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,c):
    p=Product.objects.filter(category__cname=c)
    category=Category.objects.get(cname=c)
    return render(request,'products.html',{'p':p,'category':category})
def detail(request,p):
    d=Product.objects.get(pname=p)
    return render(request,'detail.html',{'d':d})

def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        p1=request.POST['p1']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']
        if(p==p1):
            u=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            u.save()
            return allprodcat(request)

    return render(request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return allprodcat(request)
        else:
            messages.error(request,"Invalid credentials")

    return render(request,'login.html')
@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bungee+Spice&family=PT+Sans:ital@0;1&family=Poppins:ital,wght@1,100&family=Roboto+Slab&family=Roboto:wght@100;400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>
<div class="container-fluid">
    <header>
    <center>
        <img src="{% static 'images/logo4.jpg' %}" height="100px" width="120px">
    </center></div>
        <nav class="navbar navbar-expand-lg navbar-light bg-secondary mt-1">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:allprodcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.cname %}">{{i.cname}}</a></li>
              {% endfor %}

          </ul>
            {% if user.is_authenticated %}
          {% if user.is_superuser != True %}
          <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'cart:cart_view' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i>{{count}}</a>
        </li>
           <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'cart:orderview' %}">Your orders</a>
        </li>
          {% endif %}
           <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:logout' %}">logout</a>
        </li>
          {% else %}
        </li>
           <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
           <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:login' %}">login</a>

          {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:searchresult' %}">
       {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-danger" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}
<footer>
    <div class="footer">
        <p><i class="fa fa-copyright" aria-hidden="true"></i>MyShop Private Limited.All rights Reserverd.</p>
    </div>
</footer>







</body>
</html>

ecommerce/templates/cartview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not cart %}
<div>
    <h1 class="text-center">Cart is Empty</h1>
    <strong><a href="{% url 'shop:allprodcat' %}">Continue Shopping</a></strong>
</div>
{% else %}
<div class="container-fluid" style="margin-bottom:100px;">
<div class="row">


    <h3 class="text-center mt-3">Shopping Cart</h3>


    <div class="col-sm-6">
        <table class="table table-bordered">
        <tr><th colspan="5" class="text-center">CART ITEMS</th></tr>
        {% for i in cart %}

        <tr>
            <td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
            <td><p><strong>{{i.product.pname}}</strong></p></td>
            <td><p><strong>Product Id:{{i.product.id}}</strong></p>

            <p><strong>Unit Price:{{i.product.price}}</strong></p>
            <p><strong>Quantity:{{i.quantity}}*{{i.product.price}}</strong></p></td>
            <td><p><strong>{{i.subtotal}}</strong></p></td>
            <td>
                {% if i.quantity < i.product.stock %}

                <a href="{% url 'cart:add_to_cart' i.product.pname %}"><i class="fa fa-plus-circle" style="color:red;margin:8px;"></i></a>
                <a href="{% url 'cart:cart_remove' i.product.pname %}"><i class="fa fa-minus-circle" style="color:red;margin:8px;" aria-hidden="true"></i></a>
                <a href="{% url 'cart:full_remove' i.product.pname %}"><i class="fa fa-trash" style="color:red;margin:8px;" aria-hidden="true"></i></a>
            {% else %}

                <a href="{% url 'cart:cart_remove' i.product.pname %}"><i class="fa fa-minus-circle" style="color:red;margin:8px;" aria-hidden="true"></i></a>
                <a href="{% url 'cart:full_remove' i.product.pname %}"><i class="fa fa-trash" style="color:red;margin:8px;" aria-hidden="true"></i></a>
                {% endif %}


            </td>

        </tr>
        {% endfor %}
    </table></div>


    <div class="col-sm-6" >
        <table class="table table-bordered">
        <tr><th class="text-center">CHECK OUT</th></tr>
        <tr>
            <td><strong>TOTAL  {{total}}</strong></td>
        </tr></table>
  <div style="position:relative;">  <a href="{% url 'cart:order_form' %}" class="btn btn-danger">Place Order</a>
    <a href="{% url 'shop:allprodcat' %}" class="btn btn-danger" style="position:absolute;right:0;">Continue Shopping</a></div>
</div></div>
    </div>
{% endif %}

{% endblock %}

ecommerce/templates/category.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/banner2.avif' %}" height="430px" width="100%">
</div>

<div class="container-fluid mt-4" style="margin-bottom:60px;">
    <h3 class="text-center text-uppercase mb-2">Our Collections</h3>
    <p style="text-align:justify;line-height:1.7;">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
</div>

<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">
            <div class="card" style="width:30rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="250px" width=100%" alt="...">
  <div class="card-body">
    <h4 class="card-title text-center text-uppercase">{{i.cname}}</h4>
    <p class="card-text">{{i.description}}</p>
    <a href="{% url 'shop:allproducts' i.cname %}" style="position:relative;left:35%;" class="btn btn-primary">PRODUCTS</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-sm-5">
            <img src="{{d.image.url}}" height="350px" width="370px">
        </div>
        <div class="col-sm-5 mt-3">
            <h3 class="text-uppercase mb-3">{{d.pname}}</h3>
            <h5 class="mb-3">Product Description</h5>
            <p class="mb-2" style="text-align:justify;line-height:2">{{d.description}}</p>
            <h5>{{d.price}}</h5>
            {% if  user.is_superuser != True %}
                     {% if d.stock <= 0 %}
                        <h4 class="mt-2">OUT OF STOCK</h4>
                     {% else %}

                    <a href="{% url 'cart:add_to_cart' d.pname %}" class="btn btn-danger mt-4">ADD TO CART</a>
                    {% endif %}
            {% else %}
                    {% if  d.stock <= 0 %}

                        <a href="{% url 'admin:index'  %}" class="btn btn-danger mt-4">ADD STOCK</a>
                    {% endif %}
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>LOGIN</h3>
<div style="margin-bottom:100px;">
    <form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter Username">
</div>
    <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter Password">
</div>

    <div class="mb-3">

  <input type="submit" class="form-control">
</div>

    </form>

{% if messages %}
<ul>
    {% for msg in messages %}
    <li>{{msg}}</li>
    {% endfor %}
</ul>
{% endif %}
</div>


{% endblock %}

ecommerce/templates/orderconfirm.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h3 class="text-center text-success">{{msg}}</h3>
    <h6 class="text-center text-danger">Thank You.....</h6>
    <p  class="text-center"><a href="{% url 'shop:allprodcat' %}">Continue Shopping</a></p>
</div>


{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>Add Order Details</h3>
<form method="POST">
    {% csrf_token %}

<div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control"  name="a" placeholder="Enter The Address">
</div>
<div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="text" class="form-control" name="p"  placeholder="Enter The Phonenumber">
</div>
    <div class="mb-3">
  <label class="form-label">Account Number</label>
  <input type="number" class="form-control" name="n"  placeholder="Enter The Account number">
</div>
    <div class="mb-3">

  <input class="form-control" type="submit">
</div>
</form>


{% endblock %}

ecommerce/templates/orderview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="container" style="margin-bottom:100px;">
   <div class="row">

       <h5 class="text-center">Name of the customer::{{u}}</h5>

       {% for i in o %}
       <div class="col-sm-3 py-3" style="border:2px solid gray">
           <img src="{{i.product.image.url}}" height="150px" width="150px"></center>
       </div>
       <div class="col-sm-7 text-center" style="border:2px solid gray">
           Delivery Address:{{i.address}}</br>
           Phone Number :{{i.phone}}</br>
           {{i.product.name}}</br>
           {{i.product.price}}<br>
           Qunatity Ordered:{{i.noofitems}}</br>
           Subtotal:{{i.subtotal}}</br>
           <strong class="text_primary">Ordered on {{i.date_added}}</strong><br>
           <strong class="text-success">Delivery status :{{i.delivery_status}}</strong>

       </div>

       {% endfor %}
   </div>
</div>
{% endblock %}

ecommerce/templates/products.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="mt-5">
    <img src="{{category.image.url}}" height="430px" width="100%">
</div>
<div class="container-fluid mt-5" style="margin-bottom:60px;">
      <h3 class="text-center mb-2 text-uppercase">{{category.cname}}</h3>
    <p style="text-align:justify;line-height:1.7;">{{category.description}}</p>
</div>
<div class="container-fluid mt-5" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width:30rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="250px" width=100%" alt="...">
  <div class="card-body">
    <h4 class="card-title  text-uppercase text-center">{{i.pname}}</h4>

       <p class="card-text text-center">{{i.price}}</p>
    <a href="{% url 'shop:detail' i.pname %}" style="position:relative;left:40%;" class="btn btn-primary">DETAILS</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>REGISTER</h3>
<div style="margin-bottom:100px;">
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter Username">
</div>
    <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter Password">
</div>
     <div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="p1" placeholder="Enter Confirm Password">
</div>
    <div class="mb-3">
  <label  class="form-label">First Name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter firstname">
</div>
    <div class="mb-3">
  <label  class="form-label">Last Name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter lastname">
</div>
    <div class="mb-3">
  <label  class="form-label">email</label>
  <input type="text" class="form-control" name="e" placeholder="Enter email">
</div>
    <div class="mb-3">

  <input type="submit" class="form-control">
</div>

    </form>
</div>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div>
        <h4>You have searched for {{q}}</h4>
    </div>
</center>
<div class="container-fluid mt-4">
    <div class="row">
        {% for i in p %}
          <div class="col-sm-4">
            <div class="card" style="width:30rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="250px" width=100%" alt="...">
  <div class="card-body">
    <h4 class="card-title  text-uppercase text-center">{{i.pname}}</h4>

       <p class="card-text text-center">{{i.price}}</p>
    <a href="{% url 'shop:detail' i.pname %}" style="position:relative;left:40%;" class="btn btn-primary">DETAILS</a>
  </div>
</div>
        </div>
        {% empty %}
        <h6 class="text-center text-danger">0 Results Found</h6>

        {% endfor %}
    </div>

    </div>
</div>

{% endblock %}